export const red = {
  jobTitle: 'Financial Analyst',
  Score: '38.89%',
  allSkills: [
    'Design',
    'Leadership',
    'provide technical documentation',
    'Budgeting',
    'database',
    'Software Development',
    'Data Integrity',
    'Finance',
    'Project Planning',
    'manage quantitative data',
    'Accounts Receivable',
    'SAP Basis',
    'execute analytical mathematical calculations',
    'Payroll Reporting',
    'Auditing',
    'Corporate Finance',
    'Profit And Loss Forecasting',
    'handle cash flow',
  ],
  automatableSkills: [
    'Design',
    'Leadership',
    'database',
    'Software Development',
    'Finance',
    'Auditing',
    'Corporate Finance',
  ],
  nonAutomatableSkills: [
    'provide technical documentation',
    'Budgeting',
    'Data Integrity',
    'Project Planning',
    'manage quantitative data',
    'Accounts Receivable',
    'SAP Basis',
    'execute analytical mathematical calculations',
    'Payroll Reporting',
    'Profit And Loss Forecasting',
    'handle cash flow',
  ],
};

export const yellow = {
  jobTitle: 'Associate Project Designer',
  Score: '25%',
  allSkills: [
    'Supervision',
    'Design',
    'provide technical documentation',
    'Management',
    'Site Survey',
    'Budgeting',
    'electrical wiring diagrams',
    'Editing',
    'Storages',
    'manage quantitative data',
    'Organizational Architecture',
    'Uninterruptible Power Supply',
  ],
  automatableSkills: ['Editing', 'Design', 'Management'],
  nonAutomatableSkills: [
    'Supervision',
    'provide technical documentation',
    'Budgeting',
    'Site Survey',
    'electrical wiring diagrams',
    'Storages',
    'manage quantitative data',
    'Organizational Architecture',
    'Uninterruptible Power Supply',
  ],
};

export const green = {
  jobTitle: 'MRI Technologist',
  Score: '10%',
  allSkills: [
    'Data Acquisition',
    'Preventive Maintenance',
    'provide technical documentation',
    'Quality Control',
    'communication',
    'proxy servers',
    'SAP Basis',
    'mechanical engineering',
    'Inventory Planning',
    'company policies',
  ],
  automatableSkills: ['communication'],
  nonAutomatableSkills: [
    'Data Acquisition',
    'Preventive Maintenance',
    'provide technical documentation',
    'Quality Control',
    'proxy servers',
    'SAP Basis',
    'mechanical engineering',
    'Inventory Planning',
    'company policies',
  ],
};
